### ISSUE TITLE
Resolved - Channel not showing up in Windows 8 - Added Modules to Shared Folder

### ISSUE THREAD

**Issue by IniDux** [wernerkarlheisenberg/plex-stieve#4]
I was finally able to make the channel show up in Plex . I logged-on and it is working beautifully.
Thank you very much heisenberg for creating this Bundle. I am very grateful.

This is what solved the issue for me in Windows 8.1 ( Plex Version 3.9.1 -  Server Version 1.7.5.4035 )

1 . The 'requests' folder goes inside the 'Shared' folder (outside has no effect).  Everything else that was missing, also goes inside the Shared folder. (delete the old 'request' file that was inside the Shared folder )

Chronologically, one after another my log said that the following Module was missing:
ImportError: No module named requests
ImportError: No module named urllib3
ImportError: No module named chardet
ImportError: No module named certifi 
ImportError: No module named idna

2. These are all the missing python folders I had to copy to Stievie.bundle/Contents/Libraries/Shared/ 

requests - https://github.com/requests/requests
urllib3 - https://github.com/shazow/urllib3
chardet - https://github.com/chardet/chardet
certifi - https://github.com/certifi/python-certifi
idna - https://github.com/kjd/idna

And it Worked ! No issues with login.
Everything smooth.
Thanks Again for this Bundle.

**Comment by wernerkarlheisenberg** [comment]
I close this issue and will add the solution to the previous issue as well. Many thanks for posting your solution!
