### ISSUE TITLE
No settings on hover

### ISSUE THREAD

**Issue by StevenDeRoover** [wernerkarlheisenberg/plex-stieve#9]
There seems to be no settings icon upon hovering the channel?

**Comment by wernerkarlheisenberg** [comment]
Strange... Is the icon the Stievie channel shown in the channel list? If yes, do you see other icons when hovering over the icon?

**Comment by wernerkarlheisenberg** [comment]
Has the issue been solved in the mean time?

**Comment by StevenDeRoover** [comment]
Unfortunately not. I didn't have the time to respond yet.

I do get to see the gear icon of other channels.

I remember some time ago, when fiddling with another channels' code, I didn't manage to get the settings' values from code.  Maybe now, after some Plex update, the Plex api requires another api for the settings gear?

**Comment by wernerkarlheisenberg** [comment]
What plex version are you running? I'm running Version 1.10.1.4602 where it still working fine.

**Comment by StevenDeRoover** [comment]
I uninstalled the plugin, and then installed it again.  That solved the problem.

The everlasting IT issue: "have you tried to turn it off and on again?" 😄
